name: Go

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: vault-neo4j

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: |
          go get .
      - name: Test
        run: |
          go test ./neo4j
      - name: Version Number
        env:
           GITHUB_SHA: ${{ github.sha }}
        run: |
           GITDATE=$(git show -s --format=%ci)
           DATE=$(date --date="$GITDATE" -u +"%Y%m%d")
           HASH=$(git show -s --format=%h)
           VERSION="$DATE.$HASH"
           echo "BUILD_VERSION=$VERSION >> $GITHUB_ENV"
           echo "Build version: $VERSION"       
      - name: Build Docker Image
        run: |
             make docker-build
