name: Build

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: vault-neo4j

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: |
          go get .
      - name: Test
        run: |
          go test ./neo4j      
      - name: Build Docker Image
        run: |
             make docker-build
